### ISSUE TITLE
isomorphic-fetcher is a non-existent package on NPM

### ISSUE THREAD

**Issue by grempe** [kwhitley/itty-fetcher#1]
Should be `isomorphic-fetch` in your `package.json` dependencies and not `isomorphic-fetcher`.

https://socket.dev/npm/package/isomorphic-fetch

Note also, this package is unmaintained, has no source code repo, and no README.

```
itty-fetcher on  v0.x via 🤖 v16.13.2 via 🎁 v0.1.1  ❯
npm i
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/isomorphic-fetcher - Not found
npm ERR! 404
npm ERR! 404  'isomorphic-fetcher@^3.0.0' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/glenn/.npm/_logs/2022-09-11T05_13_47_579Z-debug-0.log
```

**Comment by kwhitley** [comment]
Product of a careless search and replace - thanks for the catch!

Fixed this morning! :)

**Comment by kwhitley** [comment]
> Note also, this package is unmaintained, has no source code repo, and no README.

Thanks for the heads up!  I wasn't even aware, given the 5m+ weekly downloads... cool thing about simple libraries like that, built around stable APIs, is the maintainer can walk away for years and the package still just works :)

Until it doesn't, of course, but we're not there yet for this one (luckily)!
