### ISSUE TITLE
FormData handling

### ISSUE THREAD

**Issue by danawoodman** [kwhitley/itty-fetcher#10]
I believe right now sending FormData is broken as we are always stringifying the payload. 

I believe we want to check if the payload is `FormData` and if so, pass it as-is:

```ts
payload: payload instanceof FormData ? payload : JSON.stringify(payload)
```

We should add tests to assert this expected behavior. 

This is a placeholder for that work.

**Comment by kwhitley** [comment]
Agreed... def one of the things we need to support!

**Comment by danawoodman** [comment]
I've got this working locally, just updating/refactoring tests before I put up a PR
