### ISSUE TITLE
FormData is not defined

### ISSUE THREAD

**Issue by kwhitley** [kwhitley/itty-fetcher#16]
![image](https://user-images.githubusercontent.com/865416/194772029-5014aba4-555c-4381-999d-e163111b0920.png)

Environment: fetching through SvelteKit `+server.js` endpoints

**Comment by Crisfole** [comment]
SvelteKit provides a FormData...

https://kit.svelte.dev/docs/form-actions#anatomy-of-an-action

What do you get when you do:

```ts
const fd = await request.formData()
console.log(fd);
console.log(typeof fd);
console.log(fd.__prototype);
return { ...fd, FORM_DATA_TYPE: typeof fd, FULL_FD: fd };
```

**Comment by Crisfole** [comment]
https://github.com/sveltejs/kit/blob/c1ee512fdb3bce2702f72f1818dc25bef581f647/packages/kit/src/exports/node/polyfills.js

Here's *where* they (theoretically) perform the polyfill.

https://github.com/sveltejs/kit/blob/c1ee512fdb3bce2702f72f1818dc25bef581f647/packages/kit/src/exports/vite/dev/index.js#L31

There's where *during dev* they call 'installPolyfills'...

**Comment by danawoodman** [comment]
Weird, I don't see those issues in SK, lemme see if I can repro

**Comment by Crisfole** [comment]
@kwhitley What adapter are you using there?

**Comment by danawoodman** [comment]
Yeah if you're using the node adapter you'll need 18+
