### ISSUE TITLE
Actions expect form-encoded data (received application/json) error in SvelteKit form handler

### ISSUE THREAD

**Issue by danawoodman** [kwhitley/itty-fetcher#22]
With `v0.6.1` itty-fetcher does not appear to work with form actions. `POST`ing setting value as JSON for some inexplicable reason.

```ts
const data = new FormData();
data.set("file", new File(["hi"], "foo.txt"));
fetcher()
	.post("/preview?/upload", data)
	.then(console.log)
	.catch(console.error);
```

Fails with `Actions expect form-encoded data (received application/json)`

**Comment by danawoodman** [comment]
Believe this is because the content-type header is set to application/json

**Comment by kwhitley** [comment]
Wait, did you try 0.7.0 after my changes?

**Comment by danawoodman** [comment]
Why would the Blob change affect the form content type?
