### ISSUE TITLE
Request for options access to AbortControllers

### ISSUE THREAD

**Issue by jkauszler** [kwhitley/itty-fetcher#27]
Love the simplicity and syntax of this library! The one thing preventing me from using it some production code is a way to work with Abort Controllers. Do you have a preferred method with this library (maybe I'm over looking something) or is that a feature worth adding to your roadmap?

**Comment by kwhitley** [comment]
So I don't think we'll need to support them explicitly, for a couple reasons:

1. This lib passes any options through to native fetch, which means you can absolutely use AbortController with it already!  Just pass the signal as an option into the fetcher options (3rd) param like you would with any other fetch request...
2. While the native AbortController syntax is IMO verbose and could use some abstraction like the rest of fetch, I have to assume the need to abort requests is still rather fringe, and not a mainstream need.  Thus, to abstract this further for nice aborts, we'd be adding a bunch of precious bytes to a codebase where the vast majority would never be able to benefit from the cost.  Probably better to publish a separate wrapper library or transformRequest plugin that joins the two ideas... :)

**Comment by kwhitley** [comment]
Also should note that since we pass through options, to native fetch you can use Abort Controllers just like you could with fetch.

### AbortController with native fetch
```ts
// Step 1: Create an instance of AbortController
const controller = new AbortController()
const signal = controller.signal

// Step 2: Initiate a fetch request and pass the signal as an option
fetch('https://api.example.com/data', { signal })
  .then(response => response.json())
  .then(console.log)
  .catch(error => {
    if (error.name === 'AbortError') {
      console.log('Fetch aborted')
    } else {
      console.error('Fetch error:', error)
    }
  })

// Step 3: Abort the fetch request (this could be triggered by a user action, for example)
setTimeout(() => controller.abort(), 5000)
```

### AbortController with itty-fetcher
```js
// Step 1: Create an instance of AbortController
const controller = new AbortController()
const signal = controller.signal

// Step 2: Initiate a fetch request and pass the signal as an option (3rd argument)
fetcher()
  .get('https://api.example.com/data', {}, { signal })
  .then(console.log)
  .catch(error => {
    if (error.name === 'AbortError') {
      console.log('Fetch aborted')
    } else {
      console.error('Fetch error:', error)
    }
  })

// Step 3: Abort the fetch request (this could be triggered by a user action, for example)
setTimeout(() => controller.abort(), 5000)
```
