### ISSUE TITLE
Error if `content-type` doesn't exists

### ISSUE THREAD

**Issue by beautyfree** [kwhitley/itty-fetcher#30]
There is the includes method https://github.com/kwhitley/itty-fetcher/blob/v0.x/src/itty-fetcher.ts#L130 which try to define type of returned data, but we encountered a case where a third-party service does not return `content-type`

![image](https://user-images.githubusercontent.com/656531/211789283-a51b29c2-2038-4c41-83bd-c556745aaace.png)

**Comment by kwhitley** [comment]
Sorted via #33 :)
