### ISSUE TITLE
When auto parse is on and the response is 204 fetcher can not handle it 

### ISSUE THREAD

**Issue by deadlynjdj** [kwhitley/itty-fetcher#34]
![image](https://user-images.githubusercontent.com/44127001/233728206-6daebfae-2837-471e-a588-a69755fa62f7.png)
![image](https://user-images.githubusercontent.com/44127001/233728731-4b766d22-0269-46ca-8b7a-25ba36bcfe8b.png)

**Comment by kwhitley** [comment]
Good catch - will add handling/tests for that!
