### ISSUE TITLE
Idea: transformRequest return Promise<FetchLike>

### ISSUE THREAD

**Issue by tomlarkworthy** [kwhitley/itty-fetcher#36]
`transformRequest` mutation would be more useful if asynchronous work could be done before sending the request. For example, `aws4fetch` could be used as a request interceptor and make form a nice pluggable s3 interface. Note signing requests use subtle.crypto and introduces async execution: https://github.com/mhart/aws4fetch#promiserequest-awssigninput-init, I can expect quite a few auth header attachments might want to be able to use subtle.crypto and thus an async capable `transformRequest` function seems a generally useful ask.

**Comment by kwhitley** [comment]
As simple as awaiting the function - going out in the next release!

**Comment by kwhitley** [comment]
Live in `v0.9.x` 🚀
